name: parking_project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  table_calendar: ^3.0.9
  intl: ^0.18.1
  go_router: ^10.0.0
  dio: ^5.3.2
  bloc: ^8.1.2
  flutter_secure_storage: ^8.0.0
  internet_connection_checker: ^1.0.0+1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Golos
      fonts:
        - asset: assets/fonts/GolosText-Regular.ttf
        - asset: assets/fonts/GolosText-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/icons/



